---
development:
  cloud_name: blenno
  api_key: '921555599327281'
  api_secret: 0eqpin9Qc6Zzomf-F29FYGZqqio
  enhance_image_tag: true
  static_image_support: false
  cdn_subdomain: true
production:
  cloud_name: blenno
  api_key: '921555599327281'
  api_secret: 0eqpin9Qc6Zzomf-F29FYGZqqio
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: blenno
  api_key: '921555599327281'
  api_secret: 0eqpin9Qc6Zzomf-F29FYGZqqio
  enhance_image_tag: true
  static_image_support: false
