# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: blenno
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: blenno
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: 'pr'
  pool: 5
  username: 'pr'
  password: 'annie27147'
  host: 'pr.cryf1o0dfwj6.sa-east-1.rds.amazonaws.com'
  port: 5432
